"""Logic to apply transform generated by 'bifrost register' to an image.

Execute using the 'bifrost' executable installed by setuptools
"""

import logging
import os
import sys
import tempfile
from pathlib import Path

import ants
import h5py
import numpy as np
from skimage.exposure import equalize_adapthist

from bifrost.cli.bifrost import TransformArgs
from bifrost.io import guarded_ants_image_read, md5sum, read_affine, read_image
from bifrost.util import transpose_image, update_image_array

# hide GPUs
# os.environ["CUDA_VISIBLE_DEVICES"] = ""
# suppress tensorflow import warnings
# os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")  # 0 = all, 1 = info, 2 = warning, 3 = error


def transform(args: TransformArgs) -> None:
    # ========================================================================== #
    #                      PARSE ARGS, CONFIGURE LOGGER                          #
    # ========================================================================== #
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    stdout_handler = logging.StreamHandler(stream=sys.stdout)
    # don't log errors, those get sent to stderr
    stdout_handler.addFilter(lambda x: x.levelno < logging.WARNING)
    logger.addHandler(stdout_handler)

    error_handler = logging.StreamHandler(stream=sys.stderr)
    error_handler.setLevel(logging.WARNING)
    logger.addHandler(error_handler)

    # ========================================================================== #
    #                        CONFIGURE LOGGING VERBOSITY                         #
    # ========================================================================== #

    if args.verbose:
        stdout_handler.setLevel(logging.INFO)
    else:
        stdout_handler.setLevel(logging.CRITICAL + 1)

    if os.environ.get("BIFROST_LOG_LEVEL") is not None:
        try:
            log_level = getattr(logging, os.environ["BIFROST_LOG_LEVEL"].upper())
            logger.setLevel(log_level)
            stdout_handler.setLevel(log_level)
            error_handler.setLevel(log_level)
        except AttributeError:
            logger.error("Invalid log level specified in BIFROST_LOG_LEVEL: %s", os.environ["BIFROST_LOG_LEVEL"])
            sys.exit(1)

    # ========================================================================== #
    #                      CONFIGURE LOG FILE HANDLER                            #
    # ========================================================================== #

    if args.log is None:
        log_name = f"{Path(args.image_path).name.split('.')[0]}_apply_transform.log"
        log_path = f"{args.alignment_path}/{log_name}"
    else:
        log_path = args.log

    logger.info("Writings logs to %s", log_path)

    file_handler = logging.FileHandler(log_path)
    file_handler.setLevel(logging.DEBUG)

    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    file_handler.setFormatter(formatter)

    logger.addHandler(file_handler)

    # ========================================================================== #
    #                             INPUT VALIDATION                               #
    # ========================================================================== #

    logger.debug("Parsed args: %s", args)

    assert Path(args.alignment_path, "transform.h5").exists(), (
        f"Transform file does not exist: {Path(args.alignment_path, 'transform.h5')}"
    )

    import tensorflow as tf
    import voxelmorph as vxm
    import voxelmorph.tf.networks

    logger.info("Loading moving image: %s", args.image_path)
    moving_img = guarded_ants_image_read(args.image_path)
    logger.info("Moving image hash: %s", md5sum(args.image_path))
    logger.info("Moving image info: \n %s", repr(moving_img))

    with h5py.File(f"{args.alignment_path}/transform.h5", "r") as h5_handle:
        fixed_img = ants.from_numpy(
            np.zeros(h5_handle.attrs["fixed.shape"]),
            origin=tuple(h5_handle.attrs["fixed.origin"]),
            spacing=tuple(h5_handle.attrs["fixed.spacing"]),
            direction=h5_handle.attrs["fixed.direction"],
            has_components=h5_handle.attrs["fixed.has_components"],
        )

        resample_method = 1 if args.label_image else 3

        lobe_mask = None

        if "lobe_mask" in h5_handle:
            logger.info("Loading lobe mask")
            lobe_mask = read_image(h5_handle, "/lobe_mask")

        if h5_handle.attrs["args.downsample_to"] > 0:
            desired_spacing = (h5_handle.attrs["args.downsample_to"],) * 3

            logger.info(
                f"Resampling image. Current resolution: {moving_img.spacing}, Desired resolution: {desired_spacing}",
            )

            moving_img = ants.resample_image(moving_img, desired_spacing, interp_type=resample_method)

            fixed_img = ants.resample_image(fixed_img, desired_spacing, interp_type=resample_method)

            if isinstance(lobe_mask, ants.ANTsImage):
                logger.info(
                    f"Resampling mask. Current resolution: {lobe_mask.spacing}, Desired resolution: {desired_spacing}",
                )

                lobe_mask = ants.resample_image(lobe_mask, desired_spacing, interp_type=1)

        # ========================================================================== #
        #                                  RESCALE                                   #
        # ========================================================================== #

        if args.apply_preprocessing and not args.label_image:
            logger.info("Rescaling images")
            logger.info("Moving intensity range: %s - %s", moving_img.min(), moving_img.max())
            moving_img -= moving_img.min()
            moving_img /= moving_img.max()

        # ========================================================================== #
        #                          HISTOGRAM EQUALIZATION                            #
        # ========================================================================== #

        if args.apply_preprocessing and not args.label_image and h5_handle.attrs["args.moving_clip_limit"] > 0:
            logger.info(
                "Running moving CLAHE. Clip limit: %s",
                h5_handle.attrs["args.moving_clip_limit"],
            )

            moving_clahe = equalize_adapthist(
                moving_img.numpy(),
                # get won't throw a key error if args.clahe_kernel_size doesn't exist (it might not)
                kernel_size=h5_handle.attrs.get("args.clahe_kernel_size"),
                clip_limit=h5_handle.attrs["args.moving_clip_limit"],
            )

            moving_img = update_image_array(moving_img, moving_clahe)

        # ========================================================================== #
        #                                  AFFINE                                    #
        # ========================================================================== #

        interpolator = "nearestNeighbor" if args.label_image else "linear"

        if "affine" in h5_handle:
            logger.info("Apply affine transform")

            with tempfile.TemporaryDirectory() as tmp_dir:
                affine_path = read_affine(h5_handle, "/affine", directory=tmp_dir)
                assert isinstance(moving_img, ants.ANTsImage)
                moving_img = ants.apply_transforms(
                    fixed_img,
                    moving_img,
                    transformlist=[str(affine_path)],
                    interpolator=interpolator,
                )

                if lobe_mask is not None:
                    lobe_mask = ants.apply_transforms(
                        fixed_img,
                        lobe_mask,
                        transformlist=[str(affine_path)],
                        interpolator=interpolator,
                    )

        # ========================================================================== #
        #                        SYMMETRIC NORMALIZATION                             #
        # ========================================================================== #

        if "syn" in h5_handle:
            with tempfile.TemporaryDirectory() as tmp_dir:
                affine_path = str(read_affine(h5_handle, "/syn/affine", directory=tmp_dir))

                syn_path = str(read_image(h5_handle, "/syn/forward_warp", directory=tmp_dir))

                logger.info("Apply SyN transforms")

                moving_img = ants.apply_transforms(
                    fixed_img,
                    moving_img,
                    transformlist=[syn_path, affine_path],
                    interpolator=interpolator,
                )

                if lobe_mask is not None:
                    lobe_mask = ants.apply_transforms(
                        fixed_img,
                        lobe_mask,
                        transformlist=[syn_path, affine_path],
                        interpolator=interpolator,
                    )

        # ========================================================================== #
        #                                SYNTHMORPH                                  #
        # ========================================================================== #

        if "synthmorph" in h5_handle:
            warp = h5_handle["/synthmorph"][:]

            logger.info("Transposing image")
            assert isinstance(moving_img, ants.ANTsImage)

            optimal_transposition = np.argsort(moving_img.shape)
            inverse_transposition = np.argsort(optimal_transposition)

            moving_img = transpose_image(moving_img, optimal_transposition)

            logger.info("Applying synthmorph transform")

            with tf.device(os.environ.get("BIFROST_TF_DEVICE", "")):
                # transform label image with nearest-neighbor interpolation
                logger.info("Using nearest-neighbor interpolation")
                if args.label_image:
                    transform = vxm.networks.Transform(moving_img.shape, nb_feats=1, interp_method="nearest")
                    warped = transform.predict(
                        [
                            moving_img.numpy().reshape((1,) + moving_img.shape + (1,)),
                            warp.reshape((1,) + warp.shape),
                        ]
                    ).squeeze()

                else:
                    transform = vxm.networks.Transform(moving_img.shape, nb_feats=1)
                    warped = transform.predict(
                        [
                            moving_img.numpy().reshape((1,) + moving_img.shape + (1,)),
                            warp.reshape((1,) + warp.shape),
                        ]
                    ).squeeze()

            if isinstance(lobe_mask, ants.ANTsImage):
                lobe_mask = transpose_image(lobe_mask, optimal_transposition).numpy() > 0
                assert isinstance(lobe_mask, bool)
                warped[lobe_mask] = moving_img[lobe_mask]

            moving_img = np.transpose(warped, inverse_transposition)

        # ========================================================================== #
        #                              WRITE IMAGE                                   #
        # ========================================================================== #

        # Result path resolution
        logger.info(f"Result name:{args.result_name}")
        if args.result_name is None:
            result_path = Path(args.alignment_path, args.image_path.stem + "_transformed.nii")
        elif args.result_name.startswith(("/", "./")):
            result_path = Path(args.result_name)
            result_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            result_path = Path(args.alignment_path, args.result_name)

        # Ensure ANTsImage before write
        if not isinstance(moving_img, ants.ANTsImage):
            assert isinstance(moving_img, np.ndarray)
            assert isinstance(fixed_img, ants.ANTsImage)
            moving_img = ants.from_numpy(
                moving_img,
                origin=fixed_img.origin,
                spacing=fixed_img.spacing,
                direction=fixed_img.direction,
                has_components=fixed_img.has_components,
            )

        ants.image_write(moving_img, str(result_path))
        logger.info(f"Wrote transformed image to {result_path}")
