[build-system]
build-backend = "uv_build"
requires = [
    "uv-build>=0.9.5,<0.10",
]

[dependency-groups]
dev = [
    "ipython>=9",
    "mypy>=1.18",
    "pre-commit>=4.3",
    "pytest-xdist[psutil]>=3.8",
    "pytest>=8.4",
    "ruff>=0.14",
    "snakefmt>=0.11",
    "wat>=0.7",
]

[project]
authors = [
    { email = "a5b@stanford.edu", name = "Andrew Berger" },
    { email = "altan@uw.edu", name = "Altan Orhon" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "antspyx>=0.6.1",
    "h5py>=3",
    "loguru>=0.7",
    "numpy>1.20",
    "scikit-image>=0.22",
    "scikit-learn>=1",
    "scipy>=1.10",
    "snakemake>=9",
    "tenacity>=9",
    "tensorflow-cpu>=2.15; extra != 'cuda' and extra != 'metal'",
    "tensorflow>=2.15; extra == 'cuda' or extra == 'metal'",
    "tf-keras>=2.15",
    "tyro>=0.9",
    "voxelmorph>=0.2",
]
description = "Template building and cross-modal registration."
name = "bifrost"
readme = "README.md"
requires-python = ">=3.11,<3.13"
version = "0.1.2-alpha"

[project.license]
file = "LICENSE.md"

[project.optional-dependencies]
cuda = [
    "tensorflow[and-cuda]; platform_machine=='x86_64' and sys_platform=='linux'",
]
intelcpu = [
    "intel-extension-for-tensorflow[cpu]; platform_machine=='x86_64' and sys_platform=='linux' and python_version=='3.11'",
    "numpy<2.0; platform_machine=='x86_64' and sys_platform=='linux' and python_version=='3.11'",
]
metal = [
    "tensorflow-metal; platform_machine=='arm64' and sys_platform=='darwin'",
]

[project.scripts]
bifrost = "bifrost.cli.bifrost:main"

[project.urls]
Homepage = "https://github.com/ClandininLab/bifrost"
"Source Code" = "https://github.com/maouw/bifrost"

[tool.mypy]
mypy_path = [
    "typings",
]
python_version = 3.11
strict = true

[tool.ruff]
exclude = [
    ".stubs",
    "typings",
]
indent-width = 4
line-length = 160
target-version = "py311"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 180
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
ignore = [
    "PLR0913",
    "UP045",
]
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "PL",
    "Q",
    "UP",
]

[tool.ruff.lint.per-file-ignores]
"docs/*" = [
    "D",
]
"tests/*" = [
    "D",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
allow-magic-value-types = [
    "int",
    "str",
]

[tool.uv]
conflicts = [
    [
        { extra = "cuda" },
        { extra = "metal" },
    ],
    [
        { extra = "intelcpu" },
        { extra = "metal" },
    ],
]
override-dependencies = [
    "wrapt>=1.15.0,<2.0; sys_platform=='linux'",
]

[[tool.uv.dependency-metadata]]
name = "voxelmorph"
requires-dist = [
    "neurite@ git+https://github.com/adalca/neurite.git@682f828b7b5fa652d7205c894c7fe667f1a26251",
    "pystrum@ git+https://github.com/adalca/pystrum.git@d83bd99ce25e3c79789f6891c174c39ec7f5209b",
]
version = "0.2"

[tool.uv.sources.voxelmorph]
git = "https://github.com/voxelmorph/voxelmorph.git"
rev = "53d1b95fa734648c92fd8af4f3807b09cb56c342"
